/// <reference types="vite/client" />

/** Package version of `@penwell/draw-on`, injected at build time from ../package.json. */
declare const __DRAW_ON_VERSION__: string;

/**
 * Headings for every documentation page, generated by the `draw-on-doc-headings`
 * plugin in `vite.config.ts`. Shape matches `Heading` in `src/lib/headings.ts`;
 * it is inlined here so this file stays an ambient declaration.
 */
declare module 'virtual:draw-on-headings' {
    export const DOC_HEADINGS: Record<string, { depth: 2 | 3; id: string; text: string }[]>;
}

